In [4]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')


print("Hello")

Hello

In [6]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1thMQ4ndtgzyEM6qfoA2tfrt3MEzZY2CtxhjpCTNcS0U/gviz/tq?tqx=out:csv&sheet=Content")
print(df)

                                            Post title  \
0    𝗠𝗲𝗲𝘁 𝗟𝗶𝗰𝗵𝗲𝗻𝗴 𝗙𝗮𝗻𝗴!\n \n Licheng Fang joined Tr...
1    𝗛𝗮𝗽𝗽𝘆 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗜𝗻𝘁𝗲𝗿𝗻 𝗗𝗮𝘆!\n \n We’re excited ...
2    𝗦𝗲𝘁 𝗨𝗽 𝗳𝗼𝗿 𝗦𝘂𝗰𝗰𝗲𝘀𝘀 \n \n Each of our Summer 20...
3    𝗕𝗲𝗵𝗶𝗻𝗱-𝘁𝗵𝗲-𝗦𝗰𝗲𝗻𝗲𝘀 𝘄𝗶𝘁𝗵 𝗼𝘂𝗿 𝗦𝘂𝗺𝗺𝗲𝗿 𝗧𝗿𝗮𝗱𝗶𝗻𝗴 𝗜𝗻𝘁𝗲...
4    The Perfect Match: Pickleball and Professional...
..                                                 ...
188  ⛳ Our summer trading interns in New York got t...
189  🛎️ Ringing in 2️⃣0️⃣ Years of Trillium at Nasd...
190  Our Miami office enjoyed an outing at Rosa Sky...
191  Our summer interns were invited to tour the tr...
192  While shadowing their mentors, students from S...

                                             Post link Post type  \
0    https://www.linkedin.com/feed/update/urn:li:ac...   Organic
1    https://www.linkedin.com/feed/update/urn:li:ac...   Organic
2    https://www.linkedin.com/feed/update/urn:li:ac...   Organic
3    https://www.linkedin.com/feed/update/urn:li:ac...   Organic
4    https://www.linkedin.com/feed/update/urn:li:ac...   Organic
..                                                 ...       ...
188  https://www.linkedin.com/feed/update/urn:li:ac...   Organic
189  https://www.linkedin.com/feed/update/urn:li:ac...   Organic
190  https://www.linkedin.com/feed/update/urn:li:ac...   Organic
191  https://www.linkedin.com/feed/update/urn:li:ac...   Organic
192  https://www.linkedin.com/feed/update/urn:li:ac...   Organic

     Campaign name           Posted by Created date  Campaign start date  \
0              NaN  Rafaela Kapitanker     8/1/2025                  NaN
1              NaN  Rafaela Kapitanker    7/31/2025                  NaN
2              NaN  Rafaela Kapitanker    7/30/2025                  NaN
3              NaN  Rafaela Kapitanker    7/25/2025                  NaN
4              NaN  Rafaela Kapitanker    7/23/2025                  NaN
..             ...                 ...          ...                  ...
188            NaN        Andrew Kissh    8/29/2023                  NaN
189            NaN        Andrew Kissh    8/21/2023                  NaN
190            NaN        Andrew Kissh    8/16/2023                  NaN
191            NaN        Andrew Kissh     8/9/2023                  NaN
192            NaN        Andrew Kissh     8/3/2023                  NaN

     Campaign end date       Audience  Impressions  ...  Year  Month & Year  \
0                  NaN  All followers         4163  ...  2025      Aug 2025
1                  NaN  All followers        10969  ...  2025      Jul 2025
2                  NaN  All followers         7288  ...  2025      Jul 2025
3                  NaN  All followers         4830  ...  2025      Jul 2025
4                  NaN  All followers         2169  ...  2025      Jul 2025
..                 ...            ...          ...  ...   ...           ...
188                NaN  All followers         2453  ...  2023      Aug 2023
189                NaN  All followers         2741  ...  2023      Aug 2023
190                NaN  All followers         2015  ...  2023      Aug 2023
191                NaN  All followers         2601  ...  2023      Aug 2023
192                NaN  All followers         2732  ...  2023      Aug 2023

     Day of the week  Time of Posting  Number of Post  Emoji  Emoji Value  \
0                Fri      12:11:00 PM               1  False          NaN
1                Thu       2:02:00 PM               1  False          NaN
2                Wed      12:30:00 PM               1  False          NaN
3                Fri       2:03:00 PM               1  False          NaN
4                Wed       4:19:00 PM               1  False          NaN
..               ...              ...             ...    ...          ...
188              Tue       4:36:00 PM               1   True            ⛳
189              Mon       4:36:00 PM               1   True            📸
190              Wed      11:42:00 AM               1  False          NaN
191              Wed       8:41:00 AM               1  False          NaN
192              Thu      11:42:00 AM               1  False          NaN

     Type Emoji  Type of Post Interval Times
0             🚫          text       12:00 PM
1             🚫         video        2:00 PM
2             🚫         video       12:30 PM
3             🚫         image        2:00 PM
4             🚫         video        4:30 PM
..          ...           ...            ...
188           ⛳           NaN        4:30 PM
189           📸           NaN        4:30 PM
190           🚫           NaN       11:30 AM
191           🚫           NaN        8:30 AM
192           🚫           NaN       11:30 AM

[193 rows x 33 columns]

In [9]:
df.columns

Index(['Post title', 'Post link', 'Post type', 'Campaign name', 'Posted by',
       'Created date', 'Campaign start date', 'Campaign end date', 'Audience',
       'Impressions', 'Views', 'Offsite Views', 'Clicks',
       'Click through rate (CTR)', 'Likes', 'Comments', 'Reposts', 'Follows',
       'Engagement rate', 'Content Type', 'Post Title', 'Category',
       'Sub-Category', 'Year', 'Month & Year', 'Day of the week',
       'Time of Posting', 'Number of Post', 'Emoji', 'Emoji Value',
       'Type Emoji', 'Type of Post', 'Interval Times'],
      dtype='object')

In [10]:
df.dtypes

Post title                   object
Post link                    object
Post type                    object
Campaign name               float64
Posted by                    object
Created date                 object
Campaign start date         float64
Campaign end date           float64
Audience                     object
Impressions                   int64
Views                       float64
Offsite Views               float64
Clicks                        int64
Click through rate (CTR)    float64
Likes                         int64
Comments                      int64
Reposts                       int64
Follows                     float64
Engagement rate             float64
Content Type                 object
Post Title                   object
Category                     object
Sub-Category                 object
Year                          int64
Month & Year                 object
Day of the week              object
Time of Posting              object
Number of Post                int64
Emoji                          bool
Emoji Value                  object
Type Emoji                   object
Type of Post                 object
Interval Times               object
dtype: object

In [11]:
df.describe()

,Campaign name,Campaign start date,Campaign end date,Impressions,Views,Offsite Views,Clicks,Click through rate (CTR),Likes,Comments,Reposts,Follows,Engagement rate,Year,Number of Post
count,0.0,0.0,0.0,193.000000,25.000000,0.0,193.000000,193.000000,193.000000,193.000000,193.000000,0.0,193.000000,193.000000,193.0
mean,NaN,NaN,NaN,4373.994819,1899.480000,NaN,751.730570,0.146425,43.979275,2.243523,1.170984,NaN,0.159378,2024.170984,1.0
std,NaN,NaN,NaN,3560.848102,1381.534477,NaN,917.723769,0.124324,26.597298,3.117119,1.599736,NaN,0.123843,0.650951,0.0
min,NaN,NaN,NaN,923.000000,554.000000,NaN,12.000000,0.010000,4.000000,0.000000,0.000000,NaN,0.020000,2023.000000,1.0
25%,NaN,NaN,NaN,2024.000000,1129.000000,NaN,112.000000,0.050000,25.000000,0.000000,0.000000,NaN,0.070000,2024.000000,1.0
50%,NaN,NaN,NaN,3189.000000,1316.000000,NaN,382.000000,0.090000,38.000000,1.000000,1.000000,NaN,0.110000,2024.000000,1.0
75%,NaN,NaN,NaN,5623.000000,2266.000000,NaN,1064.000000,0.220000,57.000000,3.000000,2.000000,NaN,0.230000,2025.000000,1.0
max,NaN,NaN,NaN,20272.000000,7050.000000,NaN,5140.000000,0.560000,152.000000,26.000000,11.000000,NaN,0.570000,2025.000000,1.0

In [12]:
df.head()

,Post title,Post link,Post type,Campaign name,Posted by,Created date,Campaign start date,Campaign end date,Audience,Impressions,...,Year,Month & Year,Day of the week,Time of Posting,Number of Post,Emoji,Emoji Value,Type Emoji,Type of Post,Interval Times
0,𝗠𝗲𝗲𝘁 𝗟𝗶𝗰𝗵𝗲𝗻𝗴 𝗙𝗮𝗻𝗴!\n \n Licheng Fang joined Tr...,https://www.linkedin.com/feed/update/urn:li:ac...,Organic,NaN,Rafaela Kapitanker,8/1/2025,NaN,NaN,All followers,4163,...,2025,Aug 2025,Fri,12:11:00 PM,1,False,NaN,🚫,text,12:00 PM
1,𝗛𝗮𝗽𝗽𝘆 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗜𝗻𝘁𝗲𝗿𝗻 𝗗𝗮𝘆!\n \n We’re excited ...,https://www.linkedin.com/feed/update/urn:li:ac...,Organic,NaN,Rafaela Kapitanker,7/31/2025,NaN,NaN,All followers,10969,...,2025,Jul 2025,Thu,2:02:00 PM,1,False,NaN,🚫,video,2:00 PM
2,𝗦𝗲𝘁 𝗨𝗽 𝗳𝗼𝗿 𝗦𝘂𝗰𝗰𝗲𝘀𝘀 \n \n Each of our Summer 20...,https://www.linkedin.com/feed/update/urn:li:ac...,Organic,NaN,Rafaela Kapitanker,7/30/2025,NaN,NaN,All followers,7288,...,2025,Jul 2025,Wed,12:30:00 PM,1,False,NaN,🚫,video,12:30 PM
3,𝗕𝗲𝗵𝗶𝗻𝗱-𝘁𝗵𝗲-𝗦𝗰𝗲𝗻𝗲𝘀 𝘄𝗶𝘁𝗵 𝗼𝘂𝗿 𝗦𝘂𝗺𝗺𝗲𝗿 𝗧𝗿𝗮𝗱𝗶𝗻𝗴 𝗜𝗻𝘁𝗲...,https://www.linkedin.com/feed/update/urn:li:ac...,Organic,NaN,Rafaela Kapitanker,7/25/2025,NaN,NaN,All followers,4830,...,2025,Jul 2025,Fri,2:03:00 PM,1,False,NaN,🚫,image,2:00 PM
4,The Perfect Match: Pickleball and Professional...,https://www.linkedin.com/feed/update/urn:li:ac...,Organic,NaN,Rafaela Kapitanker,7/23/2025,NaN,NaN,All followers,2169,...,2025,Jul 2025,Wed,4:19:00 PM,1,False,NaN,🚫,video,4:30 PM

In [14]:
df = df[['Post title', 'Post link', 'Created date', 'Impressions', 'Clicks',
       'Click through rate (CTR)', 'Likes',
       'Engagement rate', 'Category',
       'Sub-Category', 'Year', 'Month & Year', 'Day of the week',
       'Time of Posting', 'Emoji', 'Type of Post']].copy()

In [15]:
df.head(5)

,Post title,Post link,Created date,Impressions,Clicks,Click through rate (CTR),Likes,Engagement rate,Category,Sub-Category,Year,Month & Year,Day of the week,Time of Posting,Emoji,Type of Post
0,𝗠𝗲𝗲𝘁 𝗟𝗶𝗰𝗵𝗲𝗻𝗴 𝗙𝗮𝗻𝗴!\n \n Licheng Fang joined Tr...,https://www.linkedin.com/feed/update/urn:li:ac...,8/1/2025,4163,2013,0.48,28,0.49,Trillium Cares,Spotlights,2025,Aug 2025,Fri,12:11:00 PM,False,text
1,𝗛𝗮𝗽𝗽𝘆 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗜𝗻𝘁𝗲𝗿𝗻 𝗗𝗮𝘆!\n \n We’re excited ...,https://www.linkedin.com/feed/update/urn:li:ac...,7/31/2025,10969,1404,0.13,86,0.14,Internship,NFL Style Intro Video,2025,Jul 2025,Thu,2:02:00 PM,False,video
2,𝗦𝗲𝘁 𝗨𝗽 𝗳𝗼𝗿 𝗦𝘂𝗰𝗰𝗲𝘀𝘀 \n \n Each of our Summer 20...,https://www.linkedin.com/feed/update/urn:li:ac...,7/30/2025,7288,594,0.08,68,0.09,Internship,Field trips/events,2025,Jul 2025,Wed,12:30:00 PM,False,video
3,𝗕𝗲𝗵𝗶𝗻𝗱-𝘁𝗵𝗲-𝗦𝗰𝗲𝗻𝗲𝘀 𝘄𝗶𝘁𝗵 𝗼𝘂𝗿 𝗦𝘂𝗺𝗺𝗲𝗿 𝗧𝗿𝗮𝗱𝗶𝗻𝗴 𝗜𝗻𝘁𝗲...,https://www.linkedin.com/feed/update/urn:li:ac...,7/25/2025,4830,213,0.07,37,0.08,Internship,BTS - Case Studies,2025,Jul 2025,Fri,2:03:00 PM,False,image
4,The Perfect Match: Pickleball and Professional...,https://www.linkedin.com/feed/update/urn:li:ac...,7/23/2025,2169,114,0.07,19,0.08,Trillium Cares,Atlas Fellows,2025,Jul 2025,Wed,4:19:00 PM,False,video